<a href="https://colab.research.google.com/github/pratikshanikum16/image_classification-using-SVM/blob/main/Image_classification_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install bing-image-downloader
!mkdir images

In [ ]:
from bing_image_downloader import downloader
downloader.download('cat',limit=30,output_dir='images',adult_filter_off=True)

In [ ]:
from bing_image_downloader import downloader
downloader.download('dog',limit=30,output_dir='images',adult_filter_off=True)

In [ ]:
from bing_image_downloader import downloader
downloader.download('fish',limit=30,output_dir='images',adult_filter_off=True)

In [ ]:
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from skimage.io import imread
from skimage.transform import resize
target=[]
images=[]
flat_data=[]

dir ='/content/images'

In [ ]:
categories =['cat','dog','fish']


In [ ]:
for category in categories:
   label=categories.index(category)
   path = os.path.join(dir,category)
   for img in os.listdir(path):
        img_array=imread(os.path.join(path,img))
        img_resized=resize(img_array,(150,150,3))
        flat_data.append(img_resized.flatten())
        images.append(img_resized)
        target.append(label)
flat_data=np.array(flat_data)
target=np.array(target)
images=np.array(images)
flat_data[0]

array([0.15686275, 0.15294118, 0.09411765, ..., 0.18813072, 0.18473203,
       0.12601307])

In [ ]:
np.unique(target,return_counts=True)

(array([0, 1, 2]), array([31, 34, 43]))

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train, y_test= train_test_split(flat_data,target,test_size=0.2,random_state=109)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid= [
             {'C':[1,10,100,1000],'kernel':['linear']},                 
              {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']}, 
]

svc=svm.SVC(probability=True)
clf =GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
y_pred =clf.predict(x_test)
y_pred

array([2, 0, 2, 2, 0, 2, 2, 1, 2, 2, 2, 0, 1, 0, 2, 2, 2, 1, 0, 1, 1, 1])

In [ ]:
y_test

array([2, 0, 2, 1, 0, 2, 2, 1, 2, 2, 2, 0, 1, 0, 2, 2, 2, 1, 0, 1, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
accuracy_score(y_pred,y_test)
c_m=confusion_matrix(y_pred,y_test)
c_m

<function classification_report at 0x7ff19f042b00>


In [ ]:
accuracy_score(y_pred,y_test)

0.9545454545454546

In [ ]:
c_m

array([[ 5,  0,  0],
       [ 0,  6,  0],
       [ 0,  1, 10]])

In [ ]:
#testing
flat_data=[]
url=input('enter your URL')
img =imread(url)
flat_data.append(img_resized.flatten())
flat_data =np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out = model.predict(flat_data)
y_out =categories[y_out[0]]
print(f'PREDICTED OUTPUT: {y_out}')